### ISSUE TITLE
Missing util/hyperparams?

### ISSUE THREAD

**Issue by stevenpjg** [inikdom/neural-sentiment#23]
Hi Domnik,
     I am wondering if the hyper parameters should be added from our side or is it missing from the repository (under util/hyperparams.py). Thank you for the code.

Steven

**Comment by domerin0** [comment]
Yes, sorry about that. It seems I left it out of my last commit. I'm making a few fixes right now and will have it up soon.

**Comment by domerin0** [comment]
resolved with commit: d16b7b2441327b7c69dc8810ad92d83dbe8acdb7
