### ISSUE TITLE
Problem with tensorflow version 0.12 head

### ISSUE THREAD

**Issue by lalchand-pandia** [inikdom/neural-sentiment#28]
Hi, I have installed tensorflow from source.
In the sentiment.py I had to change tf.contrib.rnn.LSTMCell, tf.contrib.rnn.DropoutWrapper, tf.contrib.rnn.MultiRNNCell at line 75. But cannot find any replacement for rnn.rnn. I have tried tf.nn.rnn but it gave an error "'module' object has no attribute 'rnn' ". I have also tried tf.contrib.rnn but got an error "'module' object is not callable "

**Comment by domerin0** [comment]
Ok, I've noticed something always breaks when TensorFlow updates. I will take a look when I can, but I can't make any promises on timeline due to busy schedule. If there is a quick fix, I will most likely be fast about it though.

**Comment by lalchand-pandia** [comment]
I have fixed the code and will let you know the changes

**Comment by nabihach** [comment]
@lalchand-pandia Could you please create a pull request with the changes?

**Comment by domerin0** [comment]
I've updated this project to work with the latest tensorflow version (1.2), admittedly it's a bit late in coming. This should fix this issue, assuming you have the latest version of tensorflow. Feel free to reopen this issue if it is not resolved after updating.
