### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by nabihach** [inikdom/neural-sentiment#30]
Which tensorflow version should we use with this code?

**Comment by domerin0** [comment]
On my machine, I have been using 0.1:
``` 
>>> tensorflow.__version__
'0.10.0rc0'
```
I've recently tested with 0.12, and I get quite a few warnings. It seems to run ok, but I haven't had time yet to fix the specific warnings. As such, I still recommend 0.1.

**Comment by domerin0** [comment]
I have updated this to work with tensorflow 1.2, I am closing this issue as it is the latest version of tensorflow. If you run into any issue feel free to start another issue, or reopen this one.
