### ISSUE TITLE
checkpoint names

### ISSUE THREAD

**Issue by nabihach** [inikdom/neural-sentiment#31]
I made some changes to your code to run it on Tensorflow 1.0.1. Training works fine, and I see checkpoints getting saved in the data/checkpoints/ folder as follows:

```
sentiment0.501447366256.ckpt-50.data-00000-of-00001
sentiment0.501447366256.ckpt-50.index
sentiment0.501447366256.ckpt-50.meta
sentiment0.494999998494.ckpt-100.data-00000-of-00001
sentiment0.494999998494.ckpt-100.index
sentiment0.494999998494.ckpt-100.meta
```

However, in the checkpoints file, the checkpoint names are saved as follows:

```
model_checkpoint_path: "sentiment0.494999998494.ckpt-100"
all_model_checkpoint_paths: "sentiment0.501447366256.ckpt-50"
all_model_checkpoint_paths: "sentiment0.494999998494.ckpt-100"
```

Now when I run `python sample.py` , it says model not found, please check that your `checkpoint_dir` is right. Why is this happening? I tried adding `".meta"` or `".index"` to the end of `model_checkpoint_path`. Then the model is found but there are other errors and the model doesn't get loaded. Any idea why this is happening?

**Comment by nabihach** [comment]
Never mind, I was able to solve the issue after reading this: http://stackoverflow.com/questions/41265035/tensorflow-why-there-are-3-files-after-saving-the-model

**Comment by xiyulangzi** [comment]
as @nabihach  pointed out, the fix/workaround with TF1.0  can be done like below to comment out the gFile.Exists check.

works ok with my 14.04LTS + TF1.0  (notes few other changes needed to adapt to TF1.0 which can be easily done)

```
	#if ckpt and gfile.Exists(ckpt.model_checkpoint_path):
	if ckpt :    #fixed as the 3 files saved instead of one.
		print "Reading model parameters from {0}".format(ckpt.model_checkpoint_path)
		model.saver.restore(session, ckpt.model_checkpoint_path)
	else:
		print "Double check you got the checkpoint_dir right..."
		print "Model not found..."
		model = None
	return model

```
