### ISSUE TITLE
There is no restoreHyperParameters function in the sample.py

### ISSUE THREAD

**Issue by WestbrookZero** [inikdom/neural-sentiment#32]
There is no restoreHyperParameters function in the sample.py
def loadModel(session, vocab_size):
	hParams = restoreHyperParameters()
	model = models.sentiment.SentimentModel(int(hParams[0]), int(hParams[1]),
	float(hParams[2]), int(hParams[3]), int(hParams[4]), int(hParams[5]),
	float(hParams[6]),float(hParams[7]) ,True)
	ckpt = tf.train.get_checkpoint_state(FLAGS.checkpoint_dir)
	if ckpt and gfile.Exists(ckpt.model_checkpoint_path):
		print ("Reading model parameters from {0}".format(ckpt.model_checkpoint_path))
		model.saver.restore(session, ckpt.model_checkpoint_path)
	else:
		print ("Double check you got the checkpoint_dir right...")
		print ("Model not found...")
		model = None
	return model

**Comment by domerin0** [comment]
Are you saying that it gives you an error that the function is not found?

**Comment by WestbrookZero** [comment]
yea

**Comment by SafatMahmood** [comment]
I can not run the sample.py either....

its saying Double check you got the checkpoint_dir right...
Model not found..

but dir is perfect.Help please

**Comment by domerin0** [comment]
I've been away on a trip. I'll be back Monday, and can take more of a look at this then. Someone else had this problem, but wasnt using Ubuntu. You may also want to check there isn't a problem with your tensorflow installation.

**Comment by domerin0** [comment]
Ok, I'm back from my trip. Hey @WestbrookZero and @SafatMahmood, what are your versions of TensorFlow and python, and what OS are you using?

**Comment by domerin0** [comment]
I'm closing this issue for now, I've updated the project to work with the latest tensorflow version. If this issue comes up still, feel free to reopen this. If you do, make sure to let me know which: python, tensorflow, and os you are using.
