### ISSUE TITLE
Code does not run with the latest Tensorflow version.

### ISSUE THREAD

**Issue by LeenaShekhar** [inikdom/neural-sentiment#33]
Mostly it breaks at wherever there is RNN cell. I am trying to fix it, but too many changes. I would suggest you to keep the repo updated if possible.

**Comment by domerin0** [comment]
This is something I also need to do for my chatbot project. I've updated the rnn_cell, and rnn references to be compatible with tf 1.2. It probably won't work with earlier versions of tensorflow anymore. The latest version on master will have the updates.
